### ISSUE TITLE
unable to use pipe in command

### ISSUE THREAD

**Issue by kaz-utashiro** [iij/iwatch#1]
コマンドの中でパイプが使えなくなっちゃったんですね。
使えた方が嬉しいけど、問題がありますかね？

**Comment by yasuoka** [comment]
名前は iwatch に戻して、リリースということにしてみました。Apple の iWatch とかぶってしまってますが、まぁ、こっちが先なので、:) 気にしないことにします。とりあえず OpenBSD 5.7 の package に入るように動く予定です。
